### ISSUE TITLE
incompatile graphics driver 

### ISSUE THREAD

**Issue by BoogieHasFun** [cub-has-injected/OldRBXIcons#2]
![image](https://user-images.githubusercontent.com/76754631/188523424-323bfcad-21a2-4775-9bd4-fcf3f786deb9.png)
i have a gtx 1650. this is very wrong.

**Comment by cub-has-injected** [comment]
Going to fix it soon, issue with shaders. When you're installing it, don't choose folder "shaders".

**Comment by cub-has-injected** [comment]
Fixed in 1.5.1 update.
